### ISSUE TITLE
Release v4 branch

### ISSUE THREAD

**Issue by asarkar** [Azure/azure-cosmos-cassandra-extensions#20]
It seems the v4 driver support work has been ongoing for several months. Is there a planned release date for this branch? I only see https://github.com/Azure/azure-cosmos-cassandra-extensions/pull/16, what are the other pending issues that are holding up the branch?

**Comment by David-Noble-at-work** [comment]
The driver-4 extensions have been released. See https://search.maven.org/artifact/com.azure/azure-cosmos-cassandra-driver-4-extensions.
